"""Tests that keep the fallback interface complete.

docs/decisions/0014-one-interface.md (point 4) is why these exist; it is not
restated here. What matters for reading them is the mechanism: the models come
from Django's app registry, never from a list written down in this file,
because a list written down in this file would be the same promise the test
exists to replace.
"""

import datetime
import re
from decimal import Decimal

import pytest
from django.apps import apps
from django.contrib import admin
from django.contrib.admin import ActionLocation  # ty: ignore[unresolved-import]  # see inventory/admin.py
from django.contrib.auth.models import User
from django.db import models
from django.http import HttpRequest
from django.test import Client, RequestFactory
from django.urls import reverse
from simple_history.models import HistoricalChanges

from inventory.models import (
    CODE_PATTERN,
    Category,
    Item,
    ItemIdentifier,
    Label,
    Location,
    StockMovement,
    StockTransaction,
    Vendor,
    VendorOffer,
    Volunteer,
)
from inventory.staging import StagedCatalogueRow, StagedSubmissionRow, UnresolvedItemString

pytestmark = pytest.mark.django_db


def _needs_admin(model: type[models.Model]) -> bool:
    """Whether ``model`` has to be registered.

    Both exemptions are properties read off the model, so a model qualifies by
    what it *is* rather than by being named in an exception list nobody
    revisits. Anything this app authors and stores has to be registered.
    """
    # Generated by django-simple-history from the model it audits, and already
    # reachable through that model's SimpleHistoryAdmin page.
    if issubclass(model, HistoricalChanges):
        return False
    # A database view owns no rows to administer, and Django refuses to
    # register a model with a composite primary key in any case.
    return model._meta.managed


def _models_needing_admin() -> list[type[models.Model]]:
    return [model for model in apps.get_app_config("inventory").get_models() if _needs_admin(model)]


@pytest.fixture
def administrator_request(rf: RequestFactory, administrator: User) -> HttpRequest:
    request = rf.get("/admin/")
    request.user = administrator
    return request


@pytest.fixture
def one_of_each_model(
    category: Category,
    item: Item,
    volunteer: Volunteer,
    warehouse: Location,
) -> dict[type[models.Model], models.Model]:
    """One saved row of every model the admin registers, to render a page against.

    A changelist renders its columns only when there is a row to render them
    for, and a change form needs something to change, so an empty database
    would let a stale ``list_display`` or a broken ``__str__`` through. The map
    is checked against the app registry below, so a new model fails the tests
    until it has an example here.
    """
    vendor = Vendor.objects.create(name="Ubiquiti")
    transaction = StockTransaction.objects.create(actor=volunteer, kind=StockTransaction.Kind.RECEIPT)
    return {
        Category: category,
        Item: item,
        ItemIdentifier: ItemIdentifier.objects.create(
            item=item,
            kind=ItemIdentifier.Kind.MFG_PART,
            value="LBE-5AC-GEN2",
        ),
        Label: Label.objects.create(code="ABC2345678", item=item),
        Location: warehouse,
        StockMovement: StockMovement.objects.create(
            transaction=transaction,
            item=item,
            quantity=Decimal("3"),
            to_location=warehouse,
        ),
        StagedCatalogueRow: StagedCatalogueRow.objects.create(row=2, source={"D": "LiteBeam"}, name="LiteBeam"),
        StagedSubmissionRow: StagedSubmissionRow.objects.create(
            row=2,
            source={"D": "Checking Out", "E": "LiteBeam"},
            taken=True,
            direction="Checking Out",
            item="LiteBeam",
        ),
        StockTransaction: transaction,
        UnresolvedItemString: UnresolvedItemString.objects.create(
            value="mast",
            reason="names one of three masts",
        ),
        Vendor: vendor,
        VendorOffer: VendorOffer.objects.create(
            item=item,
            vendor=vendor,
            unit_price=Decimal("89.99"),
            observed_at=datetime.date(2026, 1, 6),
        ),
        Volunteer: volunteer,
    }


def test_every_model_is_registered_in_the_admin() -> None:
    unregistered = sorted(model.__name__ for model in _models_needing_admin() if not admin.site.is_registered(model))

    assert not unregistered, (
        f"Not registered in inventory/admin.py: {', '.join(unregistered)}. "
        f"The admin is the fallback that has to stay complete -- see "
        f"docs/decisions/0014-one-interface.md, point 4. If one of these really "
        f"should be left out, the reason belongs in _needs_admin() as a property "
        f"of the model, not as its name."
    )


def test_the_exemptions_are_a_policy_and_not_a_pass() -> None:
    """Guards the test above against passing for the wrong reason.

    A renamed base class or an inverted condition could make ``_exemption``
    excuse every model, and the assertion above would then pass over an empty
    set while proving nothing. Excusing no model at all would mean the
    opposite: two conditions that are dead code claiming to be a policy.
    """
    exempt = [model for model in apps.get_app_config("inventory").get_models() if not _needs_admin(model)]

    assert _models_needing_admin()
    assert exempt


def test_every_registered_model_has_a_row_to_render_its_pages_with(
    one_of_each_model: dict[type[models.Model], models.Model],
) -> None:
    """Guards the two tests below against silently skipping a model."""
    missing = sorted(model.__name__ for model in _models_needing_admin() if model not in one_of_each_model)

    assert not missing, (
        f"No example row in the one_of_each_model fixture for: {', '.join(missing)}. "
        f"Add one, or the admin pages for those models are never rendered by any test."
    )


@pytest.mark.usefixtures("_static_files_are_not_collected")
def test_the_admin_refuses_to_delete_a_row_a_sticker_names(editor: Client, warehouse: Location) -> None:
    """THE ONLY SURFACE ON WHICH inventory-tng-6pr IS OBSERVABLE.

    The API exposes no DELETE at all, so an administrator's confirmation page
    is the whole of how this guard is met -- and asserting `ProtectedError`
    from the ORM says nothing about what that page does with it. This is how
    the guard got in with a claim about the page that turned out to be false
    for half the cases; see the second assertion.

    Driven through a location rather than through an item, since
    inventory-tng-k2sg took the item's confirmation page away and left nothing
    there to observe. The claim is unchanged: a shelf carries stickers too.
    What an item's own references do to a delete is `test_models.py`'s, where
    it always was.
    """
    Label.objects.create(code="PR0TECT001", location=warehouse, quantity=None)

    page = editor.get(reverse("admin:inventory_location_delete", args=[warehouse.pk]))

    assert page.status_code == 200
    body = page.content.decode()
    assert "PR0TECT001" in body, "the page does not say which sticker it is protecting"
    # No confirm button: Django renders the protected list INSTEAD of the form.
    assert 'name="post"' not in body, "the page still offers to go through with it"


@pytest.mark.usefixtures("_static_files_are_not_collected")
def test_but_names_the_movement_rather_than_the_sticker_once_stock_has_moved(
    editor: Client, item: Item, warehouse: Location, volunteer: Volunteer
) -> None:
    """The half the guide had to be corrected about, pinned so it stays true.

    `format_callback` puts an object into `perms_needed` rather than
    `protected` when its own ModelAdmin refuses deletion -- and
    `StockMovementAdmin` does, being append-only. Both delete templates test
    `perms_lacking` BEFORE `protected`, so a row that has moved stock reports a
    permissions problem about "stock movement" and never names the label at
    all. The row is still safe; the message is simply not the one that
    explains why, and an administrator reading it would not learn that a
    sticker is involved.

    A location, for the reason the test above gives.
    """
    Label.objects.create(code="PR0TECT002", location=warehouse, quantity=None)
    moved = StockTransaction.objects.create(kind=StockTransaction.Kind.CHECKOUT, actor=volunteer)
    # One location, not two: a checkout has to take stock OUT of somewhere --
    # the `inventory_movement_matches_kind` trigger -- and nothing needs a
    # destination. What matters is only that the location has been moved from.
    StockMovement.objects.create(transaction=moved, item=item, quantity=1, from_location=warehouse)

    body = editor.get(reverse("admin:inventory_location_delete", args=[warehouse.pk])).content.decode()

    assert "stock movement" in body.lower()
    assert "PR0TECT002" not in body, "if this now names the label, the guide can say so again"


@pytest.mark.usefixtures("_static_files_are_not_collected")
def test_an_item_is_retired_rather_than_deleted_and_the_admin_offers_nothing_else(
    editor: Client, administrator_request: HttpRequest, item: Item
) -> None:
    """inventory-tng-k2sg, on both of the two paths that reach a delete.

    The confirmation page and the changelist's action menu are separate routes
    to the same loss, and closing one is the mistake that leaves this looking
    done. `guides/administrator.md` tells an administrator that an item leaves
    the catalogue by going inactive; nothing else may contradict it.

    A row with nothing pointing at it, deliberately. That is the case PROTECT
    never covered -- an item catalogued a minute ago by mistake -- and so it is
    the case that says this refusal is the admin's own rather than the
    database's answering for it.
    """
    model_admin = admin.site.get_model_admin(Item)
    delete_url = reverse("admin:inventory_item_delete", args=[item.pk])

    # Both arities: the action menu asks with no object and the confirmation
    # page asks with one.
    assert not model_admin.has_delete_permission(administrator_request)
    assert not model_admin.has_delete_permission(administrator_request, item)
    assert editor.get(delete_url).status_code == 403
    # And the refusal comes before the delete, not after it.
    assert editor.post(delete_url, {"post": "yes"}).status_code == 403
    assert Item.objects.filter(pk=item.pk).exists()

    # And the way out that remains is on the form the administrator is already
    # looking at.
    change = editor.get(reverse("admin:inventory_item_change", args=[item.pk]))
    body = change.content.decode()
    assert delete_url not in body, "the change form still links to a page that refuses"
    assert 'name="active"' in body


def test_an_admin_that_refuses_a_delete_does_not_offer_the_bulk_one(
    administrator_request: HttpRequest,
) -> None:
    """The second route, held as a property rather than model by model.

    Django does filter `delete_selected` by the delete permission, so this
    passes for a `ModelAdmin` that only turned that permission off -- and that
    is exactly why it is asserted rather than assumed. `NeverDeletedAdmin`
    drops the action by name because the coupling is Django's arrangement and
    not ours, and this is what would notice either half going away.

    Read off the registry, so an admin added later is included without being
    listed here.
    """
    registered = [(model, admin.site.get_model_admin(model)) for model in _models_needing_admin()]
    refusing = [
        (model, model_admin)
        for model, model_admin in registered
        if not model_admin.has_delete_permission(administrator_request)
    ]

    assert len(refusing) >= 6, "the admins that refuse a delete have gone missing, not the action"
    for model, model_admin in refusing:
        for where in ActionLocation:
            offered = model_admin.get_actions(administrator_request, where)  # ty: ignore[too-many-positional-arguments]
            assert "delete_selected" not in offered, (
                f"{model.__name__} refuses a delete and still offers the bulk one on the {where.value.lower()}"
            )


@pytest.mark.usefixtures("_static_files_are_not_collected")
def test_every_changelist_renders(
    editor: Client,
    one_of_each_model: dict[type[models.Model], models.Model],
) -> None:
    """A stale ``list_display`` or a broken ``__str__`` only shows up here.

    Django's admin checks catch a column naming nothing at all; they cannot
    catch a ``ModelAdmin`` method or a ``__str__`` that raises on real data.
    """
    for model in _models_needing_admin():
        url = reverse(f"admin:{model._meta.app_label}_{model._meta.model_name}_changelist")

        response = editor.get(url)

        assert response.status_code == 200, f"{model.__name__} changelist: {url} returned {response.status_code}"


@pytest.mark.usefixtures("_static_files_are_not_collected")
def test_every_change_form_renders(
    editor: Client,
    one_of_each_model: dict[type[models.Model], models.Model],
) -> None:
    """Including the ledger's, which renders read-only rather than editable."""
    for model in _models_needing_admin():
        instance = one_of_each_model.get(model)
        # Skipped rather than a KeyError: whether every model has a row is
        # test_every_registered_model_has_a_row_to_render_its_pages_with's to
        # report, and failing here too would bury its message.
        if instance is None:
            continue
        url = reverse(f"admin:{model._meta.app_label}_{model._meta.model_name}_change", args=[instance.pk])

        response = editor.get(url)

        assert response.status_code == 200, f"{model.__name__} change form: {url} returned {response.status_code}"


def test_the_ledger_is_readable_in_the_admin_but_not_editable(administrator_request: HttpRequest) -> None:
    """The ledger admins offer no save button; see inventory/admin.py."""
    for model in (StockTransaction, StockMovement):
        model_admin = admin.site.get_model_admin(model)

        assert model_admin.has_view_permission(administrator_request)
        assert not model_admin.has_change_permission(administrator_request)
        assert not model_admin.has_delete_permission(administrator_request)


def test_a_correction_is_appended_as_a_transaction_not_as_a_loose_movement(
    administrator_request: HttpRequest,
) -> None:
    assert admin.site.get_model_admin(StockTransaction).has_add_permission(administrator_request)
    assert not admin.site.get_model_admin(StockMovement).has_add_permission(administrator_request)


# --------------------------------------------------------------------------
# Labels. The admin is a write path like any other, and the check constraint
# `label_code_is_crockford_base32` holds it to the same format the API mints
# to -- so the form has to be able to satisfy that and to say so when it
# cannot. See LabelAdmin in inventory/admin.py.
# --------------------------------------------------------------------------


@pytest.mark.usefixtures("_static_files_are_not_collected")
def test_the_label_add_form_arrives_holding_a_minted_code(editor: Client) -> None:
    """Nobody can invent one: the constraint refuses everything but the format."""
    page = editor.get(reverse("admin:inventory_label_add"))

    minted = page.context["adminform"].form.initial["code"]
    assert re.fullmatch(CODE_PATTERN, minted), minted


@pytest.mark.usefixtures("_static_files_are_not_collected")
def test_the_admin_prints_a_label_with_the_code_it_offered(editor: Client, item: Item) -> None:
    minted = editor.get(reverse("admin:inventory_label_add")).context["adminform"].form.initial["code"]

    response = editor.post(
        reverse("admin:inventory_label_add"),
        {"code": minted, "item": item.pk, "quantity": "100"},
    )

    assert response.status_code == 302, response.content
    assert Label.objects.get().code == minted


@pytest.mark.usefixtures("_static_files_are_not_collected")
def test_a_code_outside_the_format_is_a_form_error_and_not_an_error_page(editor: Client, item: Item) -> None:
    """The constraint would otherwise surface as an IntegrityError and a 500."""
    response = editor.post(
        reverse("admin:inventory_label_add"),
        {"code": "SHORT", "item": item.pk, "quantity": "1"},
    )

    assert response.status_code == 200
    assert response.context["adminform"].form.errors["code"]
    assert not Label.objects.exists()


@pytest.mark.usefixtures("_static_files_are_not_collected")
def test_a_printed_code_cannot_be_retyped_in_the_admin_either(editor: Client, item: Item) -> None:
    """The sticker is already on a shelf; renaming it would 404 that sticker."""
    label = Label.objects.create(code="ABC2345678", item=item)
    url = reverse("admin:inventory_label_change", args=[label.pk])

    editor.post(url, {"code": "ZZZZZZZZZZ", "item": item.pk, "quantity": "1"})

    label.refresh_from_db()
    assert label.code == "ABC2345678"


# --------------------------------------------------------------------------
# LabelForm. The admin does not pass through a serializer, so decision 0016
# has it mirror `label_quantity_iff_item` itself or meet it as a bare
# constraint error naming nothing a person can act on.
# --------------------------------------------------------------------------


@pytest.mark.django_db
def test_the_admin_empties_a_wall_label_s_quantity() -> None:
    """The model still defaults the column to 1, which the constraint forbids here.

    `LabelForm.clean` says what an administrator would meet without this.
    """
    from inventory.admin import LabelForm
    from inventory.models import Location

    room = Location.objects.create(name="Mesh room", kind=Location.Kind.ROOM)
    form = LabelForm(data={"code": "WA1132XKTZ", "location": room.pk, "quantity": "1"})

    assert form.is_valid(), form.errors
    assert form.cleaned_data["quantity"] is None
    assert form.save().quantity is None


@pytest.mark.django_db
def test_the_admin_requires_a_quantity_on_an_item_label() -> None:
    """And the mirror image, which `blank=True` on the field otherwise allows."""
    from inventory.admin import LabelForm
    from inventory.models import Category, Item

    item = Item.objects.create(name="LiteBeam", category=Category.objects.create(name="Radios"))
    form = LabelForm(data={"code": "1TEMNQTY00", "item": item.pk, "quantity": ""})

    assert not form.is_valid()
    assert "quantity" in form.errors
    assert "label_quantity_iff_item" not in str(form.errors)
