"""Tests that keep the fallback interface complete.

docs/decisions/0014-one-interface.md (point 4) is why these exist; it is not
restated here. What matters for reading them is the mechanism: the models come
from Django's app registry, never from a list written down in this file,
because a list written down in this file would be the same promise the test
exists to replace.
"""

import pytest
from django.apps import apps
from django.contrib import admin
from django.contrib.auth.models import User
from django.db import models
from django.http import HttpRequest
from django.test import RequestFactory
from simple_history.models import HistoricalChanges

from inventory.models import StockMovement, StockTransaction

pytestmark = pytest.mark.django_db


def _exemption(model: type[models.Model]) -> str | None:
    """Why ``model`` needs no admin registration, or ``None`` if it needs one.

    Both reasons are properties read off the model, so a model qualifies by
    what it *is* rather than by being named in an exception list nobody
    revisits. Anything this app authors and stores has to be registered.
    """
    if issubclass(model, HistoricalChanges):
        # Generated by django-simple-history from the model it audits, and
        # already reachable through that model's SimpleHistoryAdmin page.
        return "a generated history table, shown on the page of the model it audits"
    if not model._meta.managed:
        # A database view. It owns no rows to administer, and Django refuses to
        # register a model with a composite primary key in any case.
        return "unmanaged: a database view Django neither creates nor writes"
    return None


def _models_needing_admin() -> list[type[models.Model]]:
    return [model for model in apps.get_app_config("inventory").get_models() if _exemption(model) is None]


@pytest.fixture
def administrator() -> User:
    """Somebody holding every Django permission.

    Anything the admins below still refuse them is refused on purpose, rather
    than for want of a grant.
    """
    return User.objects.create_superuser(username="editor", password="not-a-real-password")


@pytest.fixture
def administrator_request(rf: RequestFactory, administrator: User) -> HttpRequest:
    request = rf.get("/admin/")
    request.user = administrator
    return request


def test_every_model_is_registered_in_the_admin() -> None:
    unregistered = sorted(model.__name__ for model in _models_needing_admin() if not admin.site.is_registered(model))

    assert not unregistered, (
        f"Not registered in inventory/admin.py: {', '.join(unregistered)}. "
        f"The admin is the fallback that has to stay complete -- see "
        f"docs/decisions/0014-one-interface.md, point 4. If one of these really "
        f"should be left out, the reason belongs in _exemption() as a property "
        f"of the model, not as its name."
    )


def test_the_exemptions_are_a_policy_and_not_a_pass() -> None:
    """Guards the test above against passing for the wrong reason.

    A renamed base class or an inverted condition could make ``_exemption``
    excuse every model, and the assertion above would then pass over an empty
    set while proving nothing. Excusing no model at all would mean the
    opposite: two conditions that are dead code claiming to be a policy.
    """
    exempt = [model for model in apps.get_app_config("inventory").get_models() if _exemption(model) is not None]

    assert _models_needing_admin()
    assert exempt


def test_the_ledger_is_readable_in_the_admin_but_not_editable(administrator_request: HttpRequest) -> None:
    """A trigger rejects UPDATE and DELETE on these tables, so the admin must not offer them."""
    for model in (StockTransaction, StockMovement):
        model_admin = admin.site.get_model_admin(model)

        assert model_admin.has_view_permission(administrator_request)
        assert not model_admin.has_change_permission(administrator_request)
        assert not model_admin.has_delete_permission(administrator_request)


def test_a_correction_is_appended_as_a_transaction_not_as_a_loose_movement(
    administrator_request: HttpRequest,
) -> None:
    assert admin.site.get_model_admin(StockTransaction).has_add_permission(administrator_request)
    assert not admin.site.get_model_admin(StockMovement).has_add_permission(administrator_request)
