apiVersion: v1
kind: Service
metadata:
  name: {{ include "inventory-tng.fullname" . }}-backend
  labels:
    {{- include "inventory-tng.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: {{ include "inventory-tng.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "inventory-tng.fullname" . }}-frontend
  labels:
    {{- include "inventory-tng.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: {{ include "inventory-tng.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
