# Generated by Django 6.1 on 2026-08-18 21:03

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
import simple_history.models
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Required by the trigram index on Volunteer.display_name, which backs
        # the search-first duplicate check when a volunteer adds themselves.
        # Must run before that index is created.
        TrigramExtension(),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("website", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="inventory.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCategory",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical category",
                "verbose_name_plural": "historical categories",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalItem",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[("each", "Each"), ("metre", "Metre"), ("foot", "Foot")], default="each", max_length=10
                    ),
                ),
                ("minimum_stock", models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ("reorder_quantity", models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ("active", models.BooleanField(default=True)),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Type-specific specifications. Radios, cable and hand tools have little in common.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.category",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical item",
                "verbose_name_plural": "historical items",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalVendor",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("website", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical vendor",
                "verbose_name_plural": "historical vendors",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[("each", "Each"), ("metre", "Metre"), ("foot", "Foot")], default="each", max_length=10
                    ),
                ),
                ("minimum_stock", models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ("reorder_quantity", models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ("active", models.BooleanField(default=True)),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Type-specific specifications. Radios, cable and hand tools have little in common.",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="items", to="inventory.category"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalItemIdentifier",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("mfg_part", "Manufacturer part number"),
                            ("vendor_sku", "Vendor SKU"),
                            ("legacy_nycm", "Legacy NYCM code"),
                            ("alias", "Alias"),
                            ("barcode", "Barcode"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.CharField(max_length=200)),
                (
                    "value_normalised",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Lower(django.db.models.functions.text.Trim("value")),
                        output_field=models.CharField(max_length=200),
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical item identifier",
                "verbose_name_plural": "historical item identifiers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ItemIdentifier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("mfg_part", "Manufacturer part number"),
                            ("vendor_sku", "Vendor SKU"),
                            ("legacy_nycm", "Legacy NYCM code"),
                            ("alias", "Alias"),
                            ("barcode", "Barcode"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.CharField(max_length=200)),
                (
                    "value_normalised",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Lower(django.db.models.functions.text.Trim("value")),
                        output_field=models.CharField(max_length=200),
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="identifiers", to="inventory.item"
                    ),
                ),
            ],
            options={
                "ordering": ["value"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("warehouse", "Warehouse"),
                            ("hub", "Hub"),
                            ("room", "Room"),
                            ("shelf", "Shelf"),
                            ("volunteer_custody", "Volunteer custody"),
                            ("vehicle", "Vehicle"),
                        ],
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=32, unique=True)),
                ("printed_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="inventory.item",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-printed_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalLabel",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("code", models.CharField(db_index=True, max_length=32)),
                ("printed_at", models.DateTimeField(blank=True, editable=False)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.item",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical label",
                "verbose_name_plural": "historical labels",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalVendorOffer",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("url", models.URLField(blank=True)),
                ("unit_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("units_per_order", models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ("is_preferred", models.BooleanField(default=False)),
                ("observed_at", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.item",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical vendor offer",
                "verbose_name_plural": "historical vendor offers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VendorOffer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField(blank=True)),
                ("unit_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("units_per_order", models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ("is_preferred", models.BooleanField(default=False)),
                ("observed_at", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="offers", to="inventory.item"
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="offers", to="inventory.vendor"
                    ),
                ),
            ],
            options={
                "ordering": ["item", "vendor"],
            },
        ),
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("display_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("slack_id", models.CharField(blank=True, max_length=50, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when this record is a duplicate of another volunteer.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merged_from",
                        to="inventory.volunteer",
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.AddField(
            model_name="location",
            name="held_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="custody_locations",
                to="inventory.volunteer",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalVolunteer",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("display_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("slack_id", models.CharField(blank=True, max_length=50, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Set when this record is a duplicate of another volunteer.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.volunteer",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical volunteer",
                "verbose_name_plural": "historical volunteers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLocation",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("warehouse", "Warehouse"),
                            ("hub", "Hub"),
                            ("room", "Room"),
                            ("shelf", "Shelf"),
                            ("volunteer_custody", "Volunteer custody"),
                            ("vehicle", "Vehicle"),
                        ],
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.location",
                    ),
                ),
                (
                    "held_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.volunteer",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical location",
                "verbose_name_plural": "historical locations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("parent", "name"), name="category_unique_name_within_parent", nulls_distinct=False
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=django.contrib.postgres.indexes.GinIndex(fields=["attributes"], name="item_attributes_gin"),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum_stock__gte", 0)), name="item_minimum_stock_not_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(("reorder_quantity__gt", 0)), name="item_reorder_quantity_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemidentifier",
            constraint=models.UniqueConstraint(
                fields=("value_normalised",), name="item_identifier_unique_normalised_value"
            ),
        ),
        migrations.AddConstraint(
            model_name="label",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("item__isnull", False), ("location__isnull", True)),
                    models.Q(("item__isnull", True), ("location__isnull", False)),
                    _connector="OR",
                ),
                name="label_targets_exactly_one",
            ),
        ),
        migrations.AddConstraint(
            model_name="vendoroffer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_preferred", True)), fields=("item",), name="vendor_offer_one_preferred_per_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendoroffer",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__isnull", True), ("unit_price__gte", 0), _connector="OR"),
                name="vendor_offer_unit_price_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="vendoroffer",
            constraint=models.CheckConstraint(
                condition=models.Q(("units_per_order__gt", 0)), name="vendor_offer_units_per_order_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="volunteer",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["display_name"], name="volunteer_display_name_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddConstraint(
            model_name="volunteer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email__isnull", False)),
                fields=("email",),
                name="volunteer_unique_email_when_present",
            ),
        ),
        migrations.AddConstraint(
            model_name="volunteer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slack_id__isnull", False)),
                fields=("slack_id",),
                name="volunteer_unique_slack_id_when_present",
            ),
        ),
        migrations.AddConstraint(
            model_name="volunteer",
            constraint=models.CheckConstraint(
                condition=models.Q(("merged_into", models.F("id")), _negated=True),
                name="volunteer_not_merged_into_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("parent", "name"), name="location_unique_name_within_parent", nulls_distinct=False
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("held_by__isnull", False), ("kind", "volunteer_custody")),
                    models.Q(models.Q(("kind", "volunteer_custody"), _negated=True), ("held_by__isnull", True)),
                    _connector="OR",
                ),
                name="location_held_by_iff_custody",
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                condition=models.Q(("held_by__isnull", False)),
                fields=("held_by",),
                name="location_one_custody_per_volunteer",
            ),
        ),
        # ------------------------------------------------------------------
        # Category and Location are both trees, and a cycle in either makes
        # every ancestor walk non-terminating. One function guards both: a
        # check constraint can only see a node parented to itself, which
        # leaves A -> B -> A to hang the next recursive query that runs.
        # ------------------------------------------------------------------
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION inventory_reject_tree_cycle()
            RETURNS trigger LANGUAGE plpgsql AS $$
            DECLARE
                creates_cycle boolean;
            BEGIN
                IF NEW.parent_id IS NULL THEN
                    RETURN NEW;
                END IF;
                EXECUTE format(
                    'WITH RECURSIVE ancestors(id, parent_id) AS ('
                    '    SELECT id, parent_id FROM %I WHERE id = $1'
                    '  UNION ALL'
                    '    SELECT t.id, t.parent_id FROM %I t'
                    '      JOIN ancestors a ON t.id = a.parent_id'
                    ') SELECT EXISTS (SELECT 1 FROM ancestors WHERE id = $2)',
                    TG_TABLE_NAME, TG_TABLE_NAME
                ) INTO creates_cycle USING NEW.parent_id, NEW.id;

                IF creates_cycle THEN
                    RAISE EXCEPTION
                        'that parent would create a cycle in %', TG_TABLE_NAME
                        USING ERRCODE = 'check_violation';
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE TRIGGER category_no_cycles
                BEFORE INSERT OR UPDATE ON inventory_category
                FOR EACH ROW EXECUTE FUNCTION inventory_reject_tree_cycle();

            CREATE TRIGGER location_no_cycles
                BEFORE INSERT OR UPDATE ON inventory_location
                FOR EACH ROW EXECUTE FUNCTION inventory_reject_tree_cycle();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS location_no_cycles ON inventory_location;
            DROP TRIGGER IF EXISTS category_no_cycles ON inventory_category;
            DROP FUNCTION IF EXISTS inventory_reject_tree_cycle();
            """,
        ),
    ]
