# Generated by Django 6.1 on 2026-08-18 21:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockBalance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
            ],
            options={
                "db_table": "inventory_stock_balance",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("checkout", "Check out"),
                            ("checkin", "Check in"),
                            ("receipt", "Receipt"),
                            ("consumption", "Used at a job"),
                            ("transfer", "Transfer"),
                            ("adjustment", "Adjustment"),
                            ("count", "Stock count"),
                        ],
                        max_length=20,
                    ),
                ),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.CharField(blank=True, max_length=100)),
                (
                    "job_reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Install or node this relates to, e.g. NN217.",
                        max_length=50,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("idempotency_key", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="inventory.volunteer",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "from_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements_out",
                        to="inventory.location",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="movements", to="inventory.item"
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements_in",
                        to="inventory.location",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.stocktransaction",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(fields=["-occurred_at"], name="stock_transaction_occurred"),
        ),
        migrations.AddConstraint(
            model_name="stocktransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("idempotency_key",),
                name="stock_transaction_unique_idempotency_key",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["item", "to_location"], name="stock_movement_item_to"),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["item", "from_location"], name="stock_movement_item_from"),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="stock_movement_quantity_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("from_location__isnull", False), ("to_location__isnull", False), _connector="OR"),
                name="stock_movement_has_a_side",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("from_location", models.F("to_location")), _negated=True),
                name="stock_movement_from_differs_from_to",
            ),
        ),
        # ------------------------------------------------------------------
        # Append-only enforcement. Why a trigger rather than REVOKE is in
        # docs/decisions/0008-stock-ledger-transfer-graph.md.
        #
        # Two triggers per table, because they catch different things: a row
        # trigger cannot see TRUNCATE, and a statement trigger cannot see
        # individual rows. Without the TRUNCATE pair, `manage.py flush` erases
        # the ledger without raising anything.
        # ------------------------------------------------------------------
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION inventory_ledger_append_only()
            RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
                RAISE EXCEPTION
                    'the stock ledger is append-only: % on % is not permitted; record a compensating movement instead',
                    TG_OP, TG_TABLE_NAME
                    USING ERRCODE = 'restrict_violation';
            END;
            $$;

            CREATE TRIGGER stock_transaction_append_only
                BEFORE UPDATE OR DELETE ON inventory_stocktransaction
                FOR EACH ROW EXECUTE FUNCTION inventory_ledger_append_only();

            CREATE TRIGGER stock_movement_append_only
                BEFORE UPDATE OR DELETE ON inventory_stockmovement
                FOR EACH ROW EXECUTE FUNCTION inventory_ledger_append_only();

            CREATE TRIGGER stock_transaction_append_only_truncate
                BEFORE TRUNCATE ON inventory_stocktransaction
                FOR EACH STATEMENT EXECUTE FUNCTION inventory_ledger_append_only();

            CREATE TRIGGER stock_movement_append_only_truncate
                BEFORE TRUNCATE ON inventory_stockmovement
                FOR EACH STATEMENT EXECUTE FUNCTION inventory_ledger_append_only();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS stock_movement_append_only_truncate ON inventory_stockmovement;
            DROP TRIGGER IF EXISTS stock_transaction_append_only_truncate ON inventory_stocktransaction;
            DROP TRIGGER IF EXISTS stock_movement_append_only ON inventory_stockmovement;
            DROP TRIGGER IF EXISTS stock_transaction_append_only ON inventory_stocktransaction;
            DROP FUNCTION IF EXISTS inventory_ledger_append_only();
            """,
        ),
        # ------------------------------------------------------------------
        # Balances are derived, never stored. A movement credits its
        # to_location and debits its from_location; the balance is the sum.
        #
        # No synthetic ROW_NUMBER() id: a window function without PARTITION BY
        # blocks predicate pushdown, so PostgreSQL aggregates the whole ledger
        # before filtering and the StockMovement indexes above go unused. The
        # model uses a composite primary key instead.
        # ------------------------------------------------------------------
        migrations.RunSQL(
            sql="""
            CREATE VIEW inventory_stock_balance AS
            SELECT
                item_id,
                location_id,
                SUM(quantity) AS quantity
            FROM (
                SELECT item_id, to_location_id AS location_id, quantity
                  FROM inventory_stockmovement
                 WHERE to_location_id IS NOT NULL
                UNION ALL
                SELECT item_id, from_location_id AS location_id, -quantity
                  FROM inventory_stockmovement
                 WHERE from_location_id IS NOT NULL
            ) entries
            GROUP BY item_id, location_id;
            """,
            reverse_sql="DROP VIEW IF EXISTS inventory_stock_balance;",
        ),
    ]
