# Generated by Django 6.1 on 2026-08-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_stockbalance_stocktransaction_stockmovement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallabel",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                default=1,
                help_text="How much of the item one scan of this label stands for: a packet of 100 zip ties is 100.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="label",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                default=1,
                help_text="How much of the item one scan of this label stands for: a packet of 100 zip ties is 100.",
                max_digits=12,
            ),
        ),
        migrations.AddConstraint(
            model_name="label",
            constraint=models.CheckConstraint(condition=models.Q(("quantity__gt", 0)), name="label_quantity_positive"),
        ),
        migrations.AddConstraint(
            model_name="label",
            constraint=models.CheckConstraint(
                condition=models.Q(("location__isnull", True), ("quantity", 1), _connector="OR"),
                name="label_quantity_is_one_for_a_location",
            ),
        ),
    ]
