# Generated by Django 6.1 on 2026-08-19 04:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_historicallabel_quantity_label_quantity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="volunteer",
            options={"ordering": ["display_name", "pk"]},
        ),
    ]
