# Generated by Django 6.1 on 2026-08-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_alter_volunteer_options"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stocktransaction",
            name="stock_transaction_unique_idempotency_key",
        ),
        migrations.AddConstraint(
            model_name="stocktransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("actor", "idempotency_key"),
                name="stock_transaction_unique_idempotency_key",
            ),
        ),
    ]
