# Generated by Django 6.1 on 2026-08-19 11:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_remove_stocktransaction_stock_transaction_unique_idempotency_key_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name", "pk"], "verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["name", "pk"]},
        ),
    ]
