# Generated by Django 6.1 on 2026-08-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_alter_category_options_alter_location_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="label",
            constraint=models.CheckConstraint(
                condition=models.Q(("code__regex", "^[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{10}$")),
                name="label_code_is_crockford_base32",
            ),
        ),
    ]
