# Generated by Django 6.1, then hand-edited: see the RunSQL backfill below.
#
# NOT backward compatible with the previous release, unlike 0008. That release's
# LabelSerializer requires quantity == 1 on a location label and its model
# default writes 1, both of which `label_quantity_iff_item` now refuses -- so a
# `helm rollback` leaves a release that cannot print a wall code. Rolling back
# means reversing this migration too:
#
#     manage.py migrate inventory 0008
#
# docs/deployment.md#rolling-back allows either backward compatibility or an
# explicit plan; this is the plan. Forward is safe on its own: the migration is
# atomic, so AddConstraint holds ACCESS EXCLUSIVE and an old pod's insert waits
# for the commit rather than landing inside the window the backfill opens.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_invariants_for_every_writer"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="label",
            name="label_quantity_positive",
        ),
        migrations.RemoveConstraint(
            model_name="label",
            name="label_quantity_is_one_for_a_location",
        ),
        migrations.AlterField(
            model_name="historicallabel",
            name="quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=1,
                help_text="How much of the item one scan of this label stands for: a packet of 100 zip ties is 100. Null on a location label, which stands for no quantity of anything.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="label",
            name="quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=1,
                help_text="How much of the item one scan of this label stands for: a packet of 100 zip ties is 100. Null on a location label, which stands for no quantity of anything.",
                max_digits=12,
                null=True,
            ),
        ),
        # Every location label already stores the sentinel 1, and the constraint
        # below refuses it. Nulled here, between the field widening and the
        # constraint, because neither order works on its own: the column cannot
        # hold NULL before the AlterField above, and the constraint cannot be
        # added while the sentinel is still there. Reversing puts it back, so
        # the migration runs both ways.
        migrations.RunSQL(
            sql="UPDATE inventory_label SET quantity = NULL WHERE location_id IS NOT NULL;",
            reverse_sql="UPDATE inventory_label SET quantity = 1 WHERE location_id IS NOT NULL;",
        ),
        migrations.RunSQL(
            sql="UPDATE inventory_historicallabel SET quantity = NULL WHERE location_id IS NOT NULL;",
            reverse_sql="UPDATE inventory_historicallabel SET quantity = 1 WHERE location_id IS NOT NULL;",
        ),
        migrations.AddConstraint(
            model_name="label",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__isnull", True), ("quantity__gt", 0), _connector="OR"),
                name="label_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="label",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("item__isnull", False), ("quantity__isnull", False)),
                    models.Q(("item__isnull", True), ("quantity__isnull", True)),
                    _connector="OR",
                ),
                name="label_quantity_iff_item",
            ),
        ),
    ]
