# Generated by Django 6.1 on 2026-08-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_stock_arrives_only_where_it_is_offered"),
    ]

    operations = [
        migrations.CreateModel(
            name="StagedCatalogueRow",
            fields=[
                (
                    "row",
                    models.PositiveIntegerField(
                        help_text="The row number the spreadsheet shows, counting the header as row 1.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.JSONField(help_text="The row's cells, keyed by column letter, before anything read them."),
                ),
                ("staged_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.TextField(blank=True, help_text="The catalogued name, empty where the row names nothing."),
                ),
            ],
            options={
                "ordering": ["row"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StagedSubmissionRow",
            fields=[
                (
                    "row",
                    models.PositiveIntegerField(
                        help_text="The row number the spreadsheet shows, counting the header as row 1.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.JSONField(help_text="The row's cells, keyed by column letter, before anything read them."),
                ),
                ("staged_at", models.DateTimeField(auto_now=True)),
                (
                    "taken",
                    models.BooleanField(help_text="Whether the population rule counts this row as a submission."),
                ),
                ("at", models.CharField(blank=True, max_length=64)),
                ("email", models.TextField(blank=True)),
                ("name", models.TextField(blank=True)),
                ("direction", models.TextField(blank=True)),
                ("item", models.TextField(blank=True)),
                ("quantity", models.FloatField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["row"],
                "abstract": False,
            },
        ),
    ]
