# Generated by Django 6.1 on 2026-08-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0011_stagedcataloguerow_stagedsubmissionrow"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnresolvedItemString",
            fields=[
                (
                    "value",
                    models.TextField(
                        help_text="The item string as the submission wrote it, before normalisation.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Why the rule can make nothing of it. Empty means nobody said."
                    ),
                ),
                ("noted_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["value"],
            },
        ),
    ]
