# Generated by Django 6.1 on 2026-08-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0012_unresolveditemstring"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalvolunteer",
            name="sheet_flag",
            field=models.TextField(
                blank=True,
                help_text="What the sheet import could not settle about this volunteer. Clear it once you have.",
            ),
        ),
        migrations.AddField(
            model_name="historicalvolunteer",
            name="sheet_key",
            field=models.TextField(
                blank=True,
                help_text="The spelling or address the sheet import knew this volunteer by. Set by the import, and its key.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="sheet_flag",
            field=models.TextField(
                blank=True,
                help_text="What the sheet import could not settle about this volunteer. Clear it once you have.",
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="sheet_key",
            field=models.TextField(
                blank=True,
                help_text="The spelling or address the sheet import knew this volunteer by. Set by the import, and its key.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="volunteer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sheet_key__isnull", False)),
                fields=("sheet_key",),
                name="volunteer_unique_sheet_key_when_present",
            ),
        ),
    ]
