# Generated by Django 6.1 on 2026-08-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0013_a_volunteer_the_sheet_import_knows"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalitem",
            name="sheet_flag",
            field=models.TextField(
                blank=True, help_text="What the sheet import could not settle about this item. Clear it once you have."
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="sheet_flag",
            field=models.TextField(
                blank=True, help_text="What the sheet import could not settle about this item. Clear it once you have."
            ),
        ),
    ]
