# Generated by Django 6.1 on 2026-08-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0015_a_label_outlives_the_row_it_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "identifier",
                    models.CharField(
                        editable=False,
                        help_text="The opaque name inside this device's token. Random, and says nothing about anybody.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set to stop honouring this device's token. Enrolling again is a new row.",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-enrolled_at", "pk"],
            },
        ),
    ]
