# Generated by Django 6.1 on 2026-08-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0018_the_whitespace_trim_does_not_strip"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="itemidentifier",
            index=models.Index(
                fields=["value_normalised"], name="item_identifier_prefix", opclasses=["text_pattern_ops"]
            ),
        ),
    ]
